# -*- coding: utf-8 -*-
"""aera vs price .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOYtVKi3QaUSnEI1skWpPOCWylxqfV-7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/content/aera vs price .csv")
df

x=df[["aera"]]
x

y=df[["price"]]
y

plt.title("aera vs price")
plt.xlabel("aera")
plt.ylabel("price")
plt.scatter(x,y,color="green",s=60,ec="purple")
plt.show()

from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(x,y)

pred =model.predict(x)
pred

model.predict([[2600]])

model.predict([[455444]])

plt.title("aera vs price")
plt.xlabel("aera")
plt.ylabel("price")
plt.scatter(x,y,color="green",s=60,ec="purple")
plt.plot(x,pred)
plt.show()



model.predict([[5900]])

import warnings
warnings.filterwarnings("ignore")

model.predict([[5900]])

myaera=int(input("enter the value of aera :"))
myprice=model.predict([[myaera]])
print("price is:",myprice[0])